Attribute VB_Name = "LDRS"
Option Compare Database

Public Function Überblick() As String

     With New Stringbuilder
        .Append "CREATE TABLE UEBERBLICK ( "
        .Append "[ID] INT AUTOINCREMENT,"
        .Append "[KNE] TEXT(60) PRIMARY KEY,"
        .Append "[STATUS] TEXT(20),"
        .Append "[BETREUUNG] TEXT(20),"
        .Append "[EKPA_RV] CURRENCY,"
        .Append "[EKPA_BV] CURRENCY,"
        .Append "[EKPA_IA] CURRENCY,"
        .Append "[EKPA_EWB] CURRENCY,"
        .Append "[STICH_RV] CURRENCY,"
        .Append "[STICH_BV] CURRENCY,"
        .Append "[STICH_IA] CURRENCY,"
        .Append "[STICH_EWB] CURRENCY,"
        .Append "[PAAR_RV] CURRENCY,"
        .Append "[PAAR_BV] CURRENCY,"
        .Append "[PAAR_IA] CURRENCY,"
        .Append "[PAAR_EWB] CURRENCY,"
        .Append "[WERTHALTIG] TEXT(20),"
        .Append "[BESCHREIBUNG] MEMO,"
        .Append "[ERGEBNIS] MEMO,"
        .Append "[NOTIZEN] MEMO"

        .Append " )"
        
        Überblick = .ToString
    
    End With
    
End Function

Public Function Normal() As String

     With New Stringbuilder
        .Append "CREATE TABLE NORMAL ( "
        .Append "[ID] INT AUTOINCREMENT,"
        .Append "[KNE] TEXT(60) PRIMARY KEY,"
        .Append "[E1_BP_ENTSCHEIDUNG_INT] YESNO ,"
        .Append "[E1_BP_ENTSCHEIDUNG_DOK] MEMO,"
        .Append "[E1_BP_KDF_INT] YESNO ,"
        .Append "[E1_BP_KDF_DOK] MEMO,"
        .Append "[E1_BP_RKV_INT] YESNO ,"
        .Append "[E1_BP_RKV_DOK] MEMO,"
        .Append "[E1_BP_SICHERHEITEN_INT] YESNO ,"
        .Append "[E1_BP_SICHERHEITEN_DOK] MEMO,"
        .Append "[E1_BP_UEBERWACHUNG_INT] YESNO ,"
        .Append "[E1_BP_UEBERWACHUNG_DOK] MEMO,"
        .Append "[E1_BP_ZUORDNUNG_INT] YESNO ,"
        .Append "[E1_BP_ZUORDNUNG_DOK] MEMO,"
        .Append "[E1_BP_VORSORGE_INT] YESNO ,"
        .Append "[E1_BP_VORSORGE_DOK] MEMO,"
        .Append "[E2_TP1_VOTIERUNG_INT] YESNO ,"
        .Append "[E2_TP1_VOTIERUNG_DOK] MEMO,"
        .Append "[E2_TP1_GENEHMIGUNG_INT] YESNO ,"
        .Append "[E2_TP1_GENEHMIGUNG_DOK] MEMO,"
        .Append "[E2_TP1_AAR_INT] YESNO ,"
        .Append "[E2_TP1_AAR_DOK] MEMO,"
        .Append "[E2_TP1_STRATEGIE_INT] YESNO ,"
        .Append "[E2_TP1_STRATEGIE_DOK] MEMO,"
        .Append "[E2_TP1_BERICHT_INT] YESNO ,"
        .Append "[E2_TP1_BERICHT_DOK] MEMO,"
        .Append "[E2_TP1_VERTRAG_INT] YESNO ,"
        .Append "[E2_TP1_VERTRAG_DOK] MEMO,"
        .Append "[E2_TP1_AUSZAHLUNG_INT] YESNO ,"
        .Append "[E2_TP1_AUSZAHLUNG_DOK] MEMO,"
        .Append "[E2_TP1_FORBEARANCE_INT] YESNO ,"
        .Append "[E2_TP1_FORBEARANCE_DOK] MEMO,"
        .Append "[E2_TP2_OFFENLEGUNG_INT] YESNO ,"
        .Append "[E2_TP2_OFFENLEGUNG_DOK] MEMO,"
        .Append "[E2_TP2_UNTERLAGEN_INT] YESNO ,"
        .Append "[E2_TP2_UNTERLAGEN_DOK] MEMO,"
        .Append "[E2_TP2_EINREICHUNG_INT] YESNO ,"
        .Append "[E2_TP2_EINREICHUNG_DOK] MEMO,"
        .Append "[E2_TP2_AUSWERTUNG_INT] YESNO ,"
        .Append "[E2_TP2_AUSWERTUNG_DOK] MEMO,"
        .Append "[E2_TP2_MAHNVERFAHREN_INT] YESNO ,"
        .Append "[E2_TP2_MAHNVERFAHREN_DOK] MEMO,"
        .Append "[E2_TP2_BEURTEILUNG_INT] YESNO ,"
        .Append "[E2_TP2_BEURTEILUNG_DOK] MEMO,"
        .Append "[E2_TP2_BERECHNUNG_INT] YESNO ,"
        .Append "[E2_TP2_BERECHNUNG_DOK] MEMO,"
        .Append "[E2_TP2_NACHHALTIG_INT] YESNO ,"
        .Append "[E2_TP2_NACHHALTIG_DOK] MEMO,"
        .Append "[E2_TP3_VERFAHREN_INT] YESNO ,"
        .Append "[E2_TP3_VERFAHREN_DOK] MEMO,"
        .Append "[E2_TP3_FAKTOREN_INT] YESNO ,"
        .Append "[E2_TP3_FAKTOREN_DOK] MEMO,"
        .Append "[E2_TP3_UEBERSCHREIBUNG_INT] YESNO ,"
        .Append "[E2_TP3_UEBERSCHREIBUNG_DOK] MEMO,"
        .Append "[E2_TP3_TURNUS_INT] YESNO ,"
        .Append "[E2_TP3_TURNUS_DOK] MEMO,"
        .Append "[E2_TP3_ANLASS_INT] YESNO ,"
        .Append "[E2_TP3_ANLASS_DOK] MEMO,"
        .Append "[E2_TP3_AUSFALL_INT] YESNO ,"
        .Append "[E2_TP3_AUSFALL_DOK] MEMO,"
        .Append "[E2_TP4_VERTRAEGE_INT] YESNO ,"
        .Append "[E2_TP4_VERTRAEGE_DOK] MEMO,"
        .Append "[E2_TP4_DURCHSETZBARKEIT_INT] YESNO ,"
        .Append "[E2_TP4_DURCHSETZBARKEIT_DOK] MEMO,"
        .Append "[E2_TP4_PLAUSIBILISIERUNG_INT] YESNO ,"
        .Append "[E2_TP4_PLAUSIBILISIERUNG_DOK] MEMO,"
        .Append "[E2_TP4_TURNUS_INT] YESNO ,"
        .Append "[E2_TP4_TURNUS_DOK] MEMO,"
        .Append "[E2_TP4_ANLASS_INT] YESNO ,"
        .Append "[E2_TP4_ANLASS_DOK] MEMO,"
        .Append "[E2_TP4_VERWALTUNG_INT] YESNO ,"
        .Append "[E2_TP4_VERWALTUNG_DOK] MEMO,"
        .Append "[E2_TP4_VOLLSTAENDIGKEIT_INT] YESNO ,"
        .Append "[E2_TP4_VOLLSTAENDIGKEIT_DOK] MEMO,"
        .Append "[E2_TP5_UEBERZIEHUNG_INT] YESNO ,"
        .Append "[E2_TP5_UEBERZIEHUNG_DOK] MEMO,"
        .Append "[E2_TP5_COVENANTS_INT] YESNO ,"
        .Append "[E2_TP5_COVENANTS_DOK] MEMO,"
        .Append "[E2_TP6_SYSTEMATISCH_INT] YESNO ,"
        .Append "[E2_TP6_SYSTEMATISCH_DOK] MEMO,"
        .Append "[E2_TP6_ANLASS_INT] YESNO ,"
        .Append "[E2_TP6_ANLASS_DOK] MEMO,"
        .Append "[E2_TP6_BESTANDSAUFNAHME_INT] YESNO ,"
        .Append "[E2_TP6_BESTANDSAUFNAHME_DOK] MEMO,"
        .Append "[E2_TP6_SOLL_INT] YESNO ,"
        .Append "[E2_TP6_SOLL_DOK] MEMO,"
        .Append "[E2_TP7_ERMITTLUNG_INT] YESNO ,"
        .Append "[E2_TP7_ERMITTLUNG_DOK] MEMO,"
        .Append "[E2_TP7_BESCHLUSS_INT] YESNO ,"
        .Append "[E2_TP7_BESCHLUSS_DOK] MEMO,"
        .Append "[E2_TP7_BERICHT_INT] YESNO ,"
        .Append "[E2_TP7_BERICHT_DOK] MEMO"

        .Append " )"
        
        Normal = .ToString
    
    End With

End Function

Public Function Intensiv() As String

     With New Stringbuilder
        .Append "CREATE TABLE INTENSIV ( "
        .Append "[ID] INT AUTOINCREMENT,"
        .Append "[KNE] TEXT(60) PRIMARY KEY,"
        .Append "[E1_BP_ENTSCHEIDUNG_INT] YESNO,"
        .Append "[E1_BP_ENTSCHEIDUNG_DOK] MEMO,"
        .Append "[E1_BP_KDF_INT] YESNO,"
        .Append "[E1_BP_KDF_DOK] MEMO,"
        .Append "[E1_BP_RKV_INT] YESNO,"
        .Append "[E1_BP_RKV_DOK] MEMO,"
        .Append "[E1_BP_SICHERHEITEN_INT] YESNO,"
        .Append "[E1_BP_SICHERHEITEN_DOK] MEMO,"
        .Append "[E1_BP_UEBERWACHUNG_INT] YESNO,"
        .Append "[E1_BP_UEBERWACHUNG_DOK] MEMO,"
        .Append "[E1_BP_ZUORDNUNG_INT] YESNO,"
        .Append "[E1_BP_ZUORDNUNG_DOK] MEMO,"
        .Append "[E1_BP_VORSORGE_INT] YESNO,"
        .Append "[E1_BP_VORSORGE_DOK] MEMO,"
        .Append "[E2_TP1_VOTIERUNG_INT] YESNO,"
        .Append "[E2_TP1_VOTIERUNG_DOK] MEMO,"
        .Append "[E2_TP1_GENEHMIGUNG_INT] YESNO,"
        .Append "[E2_TP1_GENEHMIGUNG_DOK] MEMO,"
        .Append "[E2_TP1_AAR_INT] YESNO,"
        .Append "[E2_TP1_AAR_DOK] MEMO,"
        .Append "[E2_TP1_STRATEGIE_INT] YESNO,"
        .Append "[E2_TP1_STRATEGIE_DOK] MEMO,"
        .Append "[E2_TP1_BERICHT_INT] YESNO,"
        .Append "[E2_TP1_BERICHT_DOK] MEMO,"
        .Append "[E2_TP1_VERTRAG_INT] YESNO,"
        .Append "[E2_TP1_VERTRAG_DOK] MEMO,"
        .Append "[E2_TP1_AUSZAHLUNG_INT] YESNO,"
        .Append "[E2_TP1_AUSZAHLUNG_DOK] MEMO,"
        .Append "[E2_TP1_MAßNAHMEN_INT] YESNO,"
        .Append "[E2_TP1_MAßNAHMEN_DOK] MEMO,"
        .Append "[E2_TP1_FORBEARANCE_INT] YESNO,"
        .Append "[E2_TP1_FORBEARANCE_DOK] MEMO,"
        .Append "[E2_TP2_OFFENLEGUNG_INT] YESNO,"
        .Append "[E2_TP2_OFFENLEGUNG_DOK] MEMO,"
        .Append "[E2_TP2_UNTERLAGEN_INT] YESNO,"
        .Append "[E2_TP2_UNTERLAGEN_DOK] MEMO,"
        .Append "[E2_TP2_EINREICHUNG_INT] YESNO,"
        .Append "[E2_TP2_EINREICHUNG_DOK] MEMO,"
        .Append "[E2_TP2_AUSWERTUNG_INT] YESNO,"
        .Append "[E2_TP2_AUSWERTUNG_DOK] MEMO,"
        .Append "[E2_TP2_MAHNVERFAHREN_INT] YESNO,"
        .Append "[E2_TP2_MAHNVERFAHREN_DOK] MEMO,"
        .Append "[E2_TP2_BEURTEILUNG_INT] YESNO,"
        .Append "[E2_TP2_BEURTEILUNG_DOK] MEMO,"
        .Append "[E2_TP2_BERECHNUNG_INT] YESNO,"
        .Append "[E2_TP2_BERECHNUNG_DOK] MEMO,"
        .Append "[E2_TP2_NACHHALTIG_INT] YESNO,"
        .Append "[E2_TP2_NACHHALTIG_DOK] MEMO,"
        .Append "[E2_TP3_VERFAHREN_INT] YESNO,"
        .Append "[E2_TP3_VERFAHREN_DOK] MEMO,"
        .Append "[E2_TP3_FAKTOREN_INT] YESNO,"
        .Append "[E2_TP3_FAKTOREN_DOK] MEMO,"
        .Append "[E2_TP3_UEBERSCHREIBUNG_INT] YESNO,"
        .Append "[E2_TP3_UEBERSCHREIBUNG_DOK] MEMO,"
        .Append "[E2_TP3_TURNUS_INT] YESNO,"
        .Append "[E2_TP3_TURNUS_DOK] MEMO,"
        .Append "[E2_TP3_ANLASS_INT] YESNO,"
        .Append "[E2_TP3_ANLASS_DOK] MEMO,"
        .Append "[E2_TP3_AUSFALL_INT] YESNO,"
        .Append "[E2_TP3_AUSFALL_DOK] MEMO,"
        .Append "[E2_TP4_VERTRAEGE_INT] YESNO,"
        .Append "[E2_TP4_VERTRAEGE_DOK] MEMO,"
        .Append "[E2_TP4_DURCHSETZBARKEIT_INT] YESNO,"
        .Append "[E2_TP4_DURCHSETZBARKEIT_DOK] MEMO,"
        .Append "[E2_TP4_PLAUSIBILISIERUNG_INT] YESNO,"
        .Append "[E2_TP4_PLAUSIBILISIERUNG_DOK] MEMO,"
        .Append "[E2_TP4_TURNUS_INT] YESNO,"
        .Append "[E2_TP4_TURNUS_DOK] MEMO,"
        .Append "[E2_TP4_ANLASS_INT] YESNO,"
        .Append "[E2_TP4_ANLASS_DOK] MEMO,"
        .Append "[E2_TP4_VERWALTUNG_INT] YESNO,"
        .Append "[E2_TP4_VERWALTUNG_DOK] MEMO,"
        .Append "[E2_TP4_VOLLSTAENDIGKEIT_INT] YESNO,"
        .Append "[E2_TP4_VOLLSTAENDIGKEIT_DOK] MEMO,"
        .Append "[E2_TP5_UEBERZIEHUNG_INT] YESNO,"
        .Append "[E2_TP5_UEBERZIEHUNG_DOK] MEMO,"
        .Append "[E2_TP5_COVENANTS_INT] YESNO,"
        .Append "[E2_TP5_COVENANTS_DOK] MEMO,"
        .Append "[E2_TP5_UEBERWACHUNG_INT] YESNO,"
        .Append "[E2_TP5_UEBERWACHUNG_DOK] MEMO,"
        .Append "[E2_TP6_SYSTEMATISCH_INT] YESNO,"
        .Append "[E2_TP6_SYSTEMATISCH_DOK] MEMO,"
        .Append "[E2_TP6_ANLASS_INT] YESNO,"
        .Append "[E2_TP6_ANLASS_DOK] MEMO,"
        .Append "[E2_TP6_BESTANDSAUFNAHME_INT] YESNO,"
        .Append "[E2_TP6_BESTANDSAUFNAHME_DOK] MEMO,"
        .Append "[E2_TP6_SOLL_INT] YESNO,"
        .Append "[E2_TP6_SOLL_DOK] MEMO,"
        .Append "[E2_TP7_ERMITTLUNG_INT] YESNO,"
        .Append "[E2_TP7_ERMITTLUNG_DOK] MEMO,"
        .Append "[E2_TP7_BESCHLUSS_INT] YESNO,"
        .Append "[E2_TP7_BESCHLUSS_DOK] MEMO,"
        .Append "[E2_TP7_BERICHT_INT] YESNO,"
        .Append "[E2_TP7_BERICHT_DOK] MEMO"

        .Append " )"
        
        Intensiv = .ToString
    
    End With
    
End Function

Public Function Sanierung() As String

     With New Stringbuilder
        .Append "CREATE TABLE SANIERUNG ( "
        .Append "[ID] INT AUTOINCREMENT,"
        .Append "[KNE] TEXT(60) PRIMARY KEY,"
        .Append "[E1_BP_ENTSCHEIDUNG_INT] YESNO,"
        .Append "[E1_BP_ENTSCHEIDUNG_DOK] MEMO,"
        .Append "[E1_BP_KDF_INT] YESNO,"
        .Append "[E1_BP_KDF_DOK] MEMO,"
        .Append "[E1_BP_RKV_INT] YESNO,"
        .Append "[E1_BP_RKV_DOK] MEMO,"
        .Append "[E1_BP_SICHERHEITEN_INT] YESNO,"
        .Append "[E1_BP_SICHERHEITEN_DOK] MEMO,"
        .Append "[E1_BP_UEBERWACHUNG_INT] YESNO,"
        .Append "[E1_BP_UEBERWACHUNG_DOK] MEMO,"
        .Append "[E1_BP_ZUORDNUNG_INT] YESNO,"
        .Append "[E1_BP_ZUORDNUNG_DOK] MEMO,"
        .Append "[E1_BP_VORSORGE_INT] YESNO,"
        .Append "[E1_BP_VORSORGE_DOK] MEMO,"
        .Append "[E2_TP1_VOTIERUNG_INT] YESNO,"
        .Append "[E2_TP1_VOTIERUNG_DOK] MEMO,"
        .Append "[E2_TP1_GENEHMIGUNG_INT] YESNO,"
        .Append "[E2_TP1_GENEHMIGUNG_DOK] MEMO,"
        .Append "[E2_TP1_AAR_INT] YESNO,"
        .Append "[E2_TP1_AAR_DOK] MEMO,"
        .Append "[E2_TP1_STRATEGIE_INT] YESNO,"
        .Append "[E2_TP1_STRATEGIE_DOK] MEMO,"
        .Append "[E2_TP1_BERICHT_INT] YESNO,"
        .Append "[E2_TP1_BERICHT_DOK] MEMO,"
        .Append "[E2_TP1_VERTRAG_INT] YESNO,"
        .Append "[E2_TP1_VERTRAG_DOK] MEMO,"
        .Append "[E2_TP1_AUSZAHLUNG_INT] YESNO,"
        .Append "[E2_TP1_AUSZAHLUNG_DOK] MEMO,"
        .Append "[E2_TP1_FAEHIGKEIT_INT] YESNO,"
        .Append "[E2_TP1_FAEHIGKEIT_DOK] MEMO,"
        .Append "[E2_TP1_KONZEPT_INT] YESNO,"
        .Append "[E2_TP1_KONZEPT_DOK] MEMO,"
        .Append "[E2_TP1_FORBEARANCE_INT] YESNO,"
        .Append "[E2_TP1_FORBEARANCE_DOK] MEMO,"
        .Append "[E2_TP2_OFFENLEGUNG_INT] YESNO,"
        .Append "[E2_TP2_OFFENLEGUNG_DOK] MEMO,"
        .Append "[E2_TP2_UNTERLAGEN_INT] YESNO,"
        .Append "[E2_TP2_UNTERLAGEN_DOK] MEMO,"
        .Append "[E2_TP2_EINREICHUNG_INT] YESNO,"
        .Append "[E2_TP2_EINREICHUNG_DOK] MEMO,"
        .Append "[E2_TP2_AUSWERTUNG_INT] YESNO,"
        .Append "[E2_TP2_AUSWERTUNG_DOK] MEMO,"
        .Append "[E2_TP2_MAHNVERFAHREN_INT] YESNO,"
        .Append "[E2_TP2_MAHNVERFAHREN_DOK] MEMO,"
        .Append "[E2_TP2_BEURTEILUNG_INT] YESNO,"
        .Append "[E2_TP2_BEURTEILUNG_DOK] MEMO,"
        .Append "[E2_TP2_BERECHNUNG_INT] YESNO,"
        .Append "[E2_TP2_BERECHNUNG_DOK] MEMO,"
        .Append "[E2_TP2_NACHHALTIG_INT] YESNO,"
        .Append "[E2_TP2_NACHHALTIG_DOK] MEMO,"
        .Append "[E2_TP3_VERFAHREN_INT] YESNO,"
        .Append "[E2_TP3_VERFAHREN_DOK] MEMO,"
        .Append "[E2_TP3_FAKTOREN_INT] YESNO,"
        .Append "[E2_TP3_FAKTOREN_DOK] MEMO,"
        .Append "[E2_TP3_UEBERSCHREIBUNG_INT] YESNO,"
        .Append "[E2_TP3_UEBERSCHREIBUNG_DOK] MEMO,"
        .Append "[E2_TP3_TURNUS_INT] YESNO,"
        .Append "[E2_TP3_TURNUS_DOK] MEMO,"
        .Append "[E2_TP3_ANLASS_INT] YESNO,"
        .Append "[E2_TP3_ANLASS_DOK] MEMO,"
        .Append "[E2_TP3_AUSFALL_INT] YESNO,"
        .Append "[E2_TP3_AUSFALL_DOK] MEMO,"
        .Append "[E2_TP4_VERTRAEGE_INT] YESNO,"
        .Append "[E2_TP4_VERTRAEGE_DOK] MEMO,"
        .Append "[E2_TP4_DURCHSETZBARKEIT_INT] YESNO,"
        .Append "[E2_TP4_DURCHSETZBARKEIT_DOK] MEMO,"
        .Append "[E2_TP4_PLAUSIBILISIERUNG_INT] YESNO,"
        .Append "[E2_TP4_PLAUSIBILISIERUNG_DOK] MEMO,"
        .Append "[E2_TP4_TURNUS_INT] YESNO,"
        .Append "[E2_TP4_TURNUS_DOK] MEMO,"
        .Append "[E2_TP4_ANLASS_INT] YESNO,"
        .Append "[E2_TP4_ANLASS_DOK] MEMO,"
        .Append "[E2_TP4_VERWALTUNG_INT] YESNO,"
        .Append "[E2_TP4_VERWALTUNG_DOK] MEMO,"
        .Append "[E2_TP4_VOLLSTAENDIGKEIT_INT] YESNO,"
        .Append "[E2_TP4_VOLLSTAENDIGKEIT_DOK] MEMO,"
        .Append "[E2_TP5_UEBERZIEHUNG_INT] YESNO,"
        .Append "[E2_TP5_UEBERZIEHUNG_DOK] MEMO,"
        .Append "[E2_TP5_COVENANTS_INT] YESNO,"
        .Append "[E2_TP5_COVENANTS_DOK] MEMO,"
        .Append "[E2_TP5_UEBERWACHUNG_INT] YESNO,"
        .Append "[E2_TP5_UEBERWACHUNG_DOK] MEMO,"
        .Append "[E2_TP5_STILL_INT] YESNO,"
        .Append "[E2_TP5_STILL_DOK] MEMO,"
        .Append "[E2_TP6_SYSTEMATISCH_INT] YESNO,"
        .Append "[E2_TP6_SYSTEMATISCH_DOK] MEMO,"
        .Append "[E2_TP6_ANLASS_INT] YESNO,"
        .Append "[E2_TP6_ANLASS_DOK] MEMO,"
        .Append "[E2_TP6_BESTANDSAUFNAHME_INT] YESNO,"
        .Append "[E2_TP6_BESTANDSAUFNAHME_DOK] MEMO,"
        .Append "[E2_TP6_SOLL_INT] YESNO,"
        .Append "[E2_TP6_SOLL_DOK] MEMO,"
        .Append "[E2_TP7_ERMITTLUNG_INT] YESNO,"
        .Append "[E2_TP7_ERMITTLUNG_DOK] MEMO,"
        .Append "[E2_TP7_BESCHLUSS_INT] YESNO,"
        .Append "[E2_TP7_BESCHLUSS_DOK] MEMO,"
        .Append "[E2_TP7_BERICHT_INT] YESNO,"
        .Append "[E2_TP7_BERICHT_DOK] MEMO"

        .Append " )"
        
        Sanierung = .ToString
    
    End With
    
End Function

Public Function Abwicklung() As String

     With New Stringbuilder
        .Append "CREATE TABLE ABWICKLUNG ( "
        .Append "[ID] INT AUTOINCREMENT,"
        .Append "[KNE] TEXT(60) PRIMARY KEY,"
        .Append "[E1_BP_ENTSCHEIDUNG_INT] YESNO,"
        .Append "[E1_BP_ENTSCHEIDUNG_DOK] MEMO,"
        .Append "[E1_BP_KDF_INT] YESNO,"
        .Append "[E1_BP_KDF_DOK] MEMO,"
        .Append "[E1_BP_RKV_INT] YESNO,"
        .Append "[E1_BP_RKV_DOK] MEMO,"
        .Append "[E1_BP_SICHERHEITEN_INT] YESNO,"
        .Append "[E1_BP_SICHERHEITEN_DOK] MEMO,"
        .Append "[E1_BP_UEBERWACHUNG_INT] YESNO,"
        .Append "[E1_BP_UEBERWACHUNG_DOK] MEMO,"
        .Append "[E1_BP_ZUORDNUNG_INT] YESNO,"
        .Append "[E1_BP_ZUORDNUNG_DOK] MEMO,"
        .Append "[E1_BP_VORSORGE_INT] YESNO,"
        .Append "[E1_BP_VORSORGE_DOK] MEMO,"
        .Append "[E2_TP1_GENEHMIGUNG_INT] YESNO,"
        .Append "[E2_TP1_GENEHMIGUNG_DOK] MEMO,"
        .Append "[E2_TP1_AAR_INT] YESNO,"
        .Append "[E2_TP1_AAR_DOK] MEMO,"
        .Append "[E2_TP1_BERICHT_INT] YESNO,"
        .Append "[E2_TP1_BERICHT_DOK] MEMO,"
        .Append "[E2_TP1_KONZEPT_INT] YESNO,"
        .Append "[E2_TP1_KONZEPT_DOK] MEMO,"
        .Append "[E2_TP1_OUTSOURCING_INT] YESNO,"
        .Append "[E2_TP1_OUTSOURCING_DOK] MEMO,"
        .Append "[E2_TP1_FORBEARANCE_INT] YESNO,"
        .Append "[E2_TP1_FORBEARANCE_DOK] MEMO,"
        .Append "[E2_TP2_RUMPFKDF_INT] YESNO,"
        .Append "[E2_TP2_RUMPFKDF_DOK] MEMO,"
        .Append "[E2_TP3_ANLASS_INT] YESNO,"
        .Append "[E2_TP3_ANLASS_DOK] MEMO,"
        .Append "[E2_TP3_AUSFALL_INT] YESNO,"
        .Append "[E2_TP3_AUSFALL_DOK] MEMO,"
        .Append "[E2_TP4_VERTRAEGE_INT] YESNO,"
        .Append "[E2_TP4_VERTRAEGE_DOK] MEMO,"
        .Append "[E2_TP4_DURCHSETZBARKEIT_INT] YESNO,"
        .Append "[E2_TP4_DURCHSETZBARKEIT_DOK] MEMO,"
        .Append "[E2_TP4_PLAUSIBILISIERUNG_INT] YESNO,"
        .Append "[E2_TP4_PLAUSIBILISIERUNG_DOK] MEMO,"
        .Append "[E2_TP4_TURNUS_INT] YESNO,"
        .Append "[E2_TP4_TURNUS_DOK] MEMO,"
        .Append "[E2_TP4_ANLASS_INT] YESNO,"
        .Append "[E2_TP4_ANLASS_DOK] MEMO,"
        .Append "[E2_TP4_VERWALTUNG_INT] YESNO,"
        .Append "[E2_TP4_VERWALTUNG_DOK] MEMO,"
        .Append "[E2_TP4_VERWERTUNG_INT] YESNO,"
        .Append "[E2_TP4_VERWERTUNG_DOK] MEMO,"
        .Append "[E2_TP4_VOLLSTAENDIGKEIT_INT] YESNO,"
        .Append "[E2_TP4_VOLLSTAENDIGKEIT_DOK] MEMO,"
        .Append "[E2_TP5_UEBERWACHUNG_INT] YESNO,"
        .Append "[E2_TP5_UEBERWACHUNG_DOK] MEMO,"
        .Append "[E2_TP5_STILL_INT] YESNO,"
        .Append "[E2_TP5_STILL_DOK] MEMO,"
        .Append "[E2_TP6_SOLL_INT] YESNO,"
        .Append "[E2_TP6_SOLL_DOK] MEMO,"
        .Append "[E2_TP7_ERMITTLUNG_INT] YESNO,"
        .Append "[E2_TP7_ERMITTLUNG_DOK] MEMO,"
        .Append "[E2_TP7_BESCHLUSS_INT] YESNO,"
        .Append "[E2_TP7_BESCHLUSS_DOK] MEMO,"
        .Append "[E2_TP7_BERICHT_INT] YESNO,"
        .Append "[E2_TP7_BERICHT_DOK] MEMO"

        .Append " )"
        
        Abwicklung = .ToString
    
    End With
    
End Function

Public Function Paar() As String

     With New Stringbuilder
        .Append "CREATE TABLE PAAR ( "
        .Append "[ID] INT AUTOINCREMENT,"
        .Append "[KNE] TEXT(60) PRIMARY KEY,"
        .Append "[DARSTELLUNG] MEMO,"
        .Append "[VERHAELTNISSE] MEMO,"
        .Append "[SICHERHEITEN] MEMO,"
        .Append "[EWB] MEMO,"
        .Append "[FESTSTELLUNGEN] MEMO"

        .Append " )"
        
        Paar = .ToString
    
    End With
    
End Function

Public Function Abstimmung() As String

     With New Stringbuilder
        .Append "CREATE TABLE ABSTIMMUNG ( "
        .Append "[ID] INT AUTOINCREMENT,"
        .Append "[KNE] TEXT(60) PRIMARY KEY,"
        .Append "[DATUM] DATE,"
        .Append "[INSTITUT] MEMO,"
        .Append "[BBK] MEMO,"
        .Append "[FRAGE] MEMO,"
        .Append "[REAKTION] MEMO,"
        .Append "[FAZIT] MEMO"
        
        .Append " )"
        
        Abstimmung = .ToString
    
    End With
    
End Function

