VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Normal"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
'@Folder("Sql")
Option Compare Database

Option Explicit
'@PredeclaredId

Public Property Get Kreditentscheidung() As IGenericValue

End Property


Public Property Set Kreditentscheidung(ByVal V As IGenericValue)

End Property
