VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IGenericPredicator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
'@Exposed
'@PredeclaredId
'@Folder "Base.Abstract"
Option Explicit

'@DefaultMember
Public Function IsTrue(ByVal A As Object, ByVal B As Object) As Boolean: End Function
Attribute IsTrue.VB_UserMemId = 0
